### PR TITLE
feat: homepage setup, fixed categories hook, adjusted random styles

### LINKED ISSUE #18: Homepage mark up

### PR DESCRIPTION
**Pull request by RedBlueKoi**

### CODE REVIEW

**Comment by RedBlueKoi** [comment]
Take a look, but please don't merge it yet. I need to finish the hooks. Make sure that the homepage works and that you can navigate to the category page

File: src/router/index.ts [hunk 1]
```diff
@@ -20,12 +20,12 @@ const router = createRouter({
       component: () => import("@/views/SuccessView.vue")
     },
     {
-      path: "/:categoryName/:productId",
+      path: "/categories/:categoryName/:productId",
```
Comment (RedBlueKoi) [inline src/router/index.ts]: Otherwise handling 404 would be a bit messy, so I decided to not overcomplicate. =/

File: src/utils/index.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
+export const getSlug = (name: string): string => {
```
Comment (RedBlueKoi) [inline src/utils/index.ts:1]: Converting human-readable name to a nice url format

File: src/views/CategoryView.vue [hunk 3]
```diff
@@ -1,7 +1,31 @@
...
+  import { useRoute, useRouter } from "vue-router"
+  import PageTitle from "@/components/PageTitle.vue"
+  import type { Category } from "@/types/products"
+
+  const { params } = useRoute()
+  const router = useRouter()
+  const { categories, areCategoriesLoading } = useCategories()
+  const currentCategory = ref<Category | undefined>(undefined)
+
+  watchEffect(() => {
```
Comment (RedBlueKoi) [inline src/views/CategoryView.vue:12]: Redirecting to 404 when can't find category or category list is empty

File: src/views/CategoryView.vue [hunk 4]
```diff
@@ -1,7 +1,31 @@
...
+    currentCategory.value = categories.value.find(
+      (category) => getSlug(category.name) === categoryName
+    )
+    if (!currentCategory.value) router.push("/not-found")
+  })
+</script>
 
 <template>
-  <h3>Category View</h3>
+  <div v-if="areCategoriesLoading">Loading...</div>
```
Comment (RedBlueKoi) [inline src/views/CategoryView.vue]: Showing preloader

File: src/views/HomeView.vue [hunk 5]
```diff
@@ -1,9 +1,29 @@
...
+  const { categories } = useCategories()
+</script>
+
 <template>
-  <main>
-    <page-title>Title</page-title>
+  <main class="px-4 py-6">
+    <page-title>Categories</page-title>
+    <div class="py-6 grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
+      <router-link
```
Comment (RedBlueKoi) [inline src/views/HomeView.vue:13]: This should become a separate component CategoryCard

File: tsconfig.app.json [hunk 6]
```diff
@@ -3,6 +3,7 @@
   "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
   "exclude": ["src/**/__tests__/*"],
   "compilerOptions": {
+    "lib": ["ES2021"],
```
Comment (RedBlueKoi) [inline tsconfig.app.json:6]: Making sure that we can use latest features of ES. In my case I needed `String.prototype.replaceAll()`

File: package.json [hunk 7]
```diff
@@ -37,6 +37,7 @@
     "eslint": "^8.5.0",
     "eslint-plugin-cypress": "^2.12.1",
     "eslint-plugin-vue": "^9.0.0",
+    "firebase": "^9.9.1",
```
Comment (RedBlueKoi) [inline package.json:40]: You might want to run `pnpm install`
